const Images = {
  user: require('../../assets/images/user.png'),
  profile: require('../../assets/images/profile.png'),
  filter: require('../../assets/images/filter.png'),
  sort: require('../../assets/images/sort.png'),
  backArrow: require('../../assets/images/arrow/arrow-left/angle-left.png'),
  rightArrow: require('../../assets/images/arrow/arrow-right/angle-right.png'),
  home: require('../../assets/images/header/home.png'),
  call: require('../../assets/images/header/call.png'),
  calender: require('../../assets/images/header/calender.png'),
  chat: require('../../assets/images/header/chat.png'),
  settings: require('../../assets/images/header/settings.png'),
  logo: require('../../assets/images/header/logo.png'),
  leftPerson: require('../../assets/images/header/leftPerson.png'),
  rightPerson: require('../../assets/images/header/rightPerson.png'),
  messages: require('../../assets/images/header/messages.png'),
  notFound: require('../../assets/images/not-found.png'),
  person: require('../../assets/images/person.png'),
  appointment: require('../../assets/images/appointment.png'),
  directoryProfile: require('../../assets/images/directoryProfile.png'),
  appointmentProfile: require('../../assets/images/appointmentProfile.png'),
  caregiverImage: require('../../assets/images/onboarding/caregiver.png'),
  patientImage: require('../../assets/images/onboarding/patient.png'),
  checkImage: require('../../assets/images/check.png'),
  medicineTakenImage: require('../../assets/images/medicineTaken.png'),
  chatImage: require('../../assets/images/chat.png'),
  microphoneImage: require('../../assets/images/microphone.gif'),
  male: require('../../assets/images/male.png'),
  female: require('../../assets/images/female.jpg'),
  demo1: require('../../assets/images/demo/01.jpg'),
  demo2: require('../../assets/images/demo/02.jpg'),
  demo3: require('../../assets/images/demo/03.jpg'),
};

export default Images;
